spring:
  application:
    name: stock-report
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

stock-report:
  service-start-date: 2026-07-01
