spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${STOCK_REPORT_DB_URL:jdbc:postgresql://localhost:5432/stock_report}
    username: ${STOCK_REPORT_DB_USERNAME:stock_report}
    password: ${STOCK_REPORT_DB_PASSWORD:stock_report}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: ${STOCK_REPORT_FLYWAY_ENABLED:true}
